new TypeIt('#typing', {
  strings: ["Malwared",
      "arcade Malwared",
      "bedwars Malwared",
      "blitz Malwared",
      "copsandcrimes Malwared",
      "crazywalls Malwared",
      "duels Malwared",
      "megawalls Malwared",
      "murdermystery Malwared",
      "skyclash Malwared",
      "skywars Malwared",
      "smashheroes Malwared",
      "speeduhc Malwared",
      "uhc Malwared",
      "hypixel verify Malwared"],
  speed: 70,
  breakLines: false,
  autoStart: true,
  lifeLike: false,
  startDelay: 250,
  loop: true,
  loopDelay: 2000,
  nextStringDelay: 2000
});
